# Generated by Django 4.1.1 on 2022-10-05 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Country_Name', models.CharField(max_length=50)),
                ('Country_Capital', models.CharField(max_length=50)),
                ('Country_Currency', models.CharField(max_length=30)),
            ],
        ),
    ]
